### ISSUE TITLE
-S parameter needs to be much larger than size of files on disk

### ISSUE THREAD

**Issue by keithsw1111** [earlephilhower/mklittlefs#16]
Maybe I am missing something here but I have on my windows machine a folder which is reported as 280,644 bytes (356,352 bytes on disk).

I run mklittlefs with the following command line:

mklittlefs.exe -c data -p 256 -b 8192 -s xxx littlefs\littlefs.img

where xxx is different values. I figured a value slightly larger than one of the sizes windows reports would be enough but through trial and error I find unless I set xxx to 606208 or greater mklittlefs reports running out of space building the file system.

Am I doing something wrong?

**Comment by earlephilhower** [comment]
This tool just passes things down to the littleFS library and doesn't actually manipulate the bits themselves.  Your question is probably best addressed in their repo.  That said, if those options are your HW's constraints, then I don't think there's much that can be done.

As a quick guess I'd check the number of files.  With `-b 8192` then each file will take 8KB IIRC, plus additional FS overhead.  Lots of 100 byte files could end up with much wasted space.
