### ISSUE TITLE
idea for a new feature uploading the sourcecode

### ISSUE THREAD

**Issue by StefanL38** [earlephilhower/mklittlefs#21]
Hi Earl,

what do you think about the idea of having a upload-tool that is able to upload the **sourcecode**-files into flash?
In most cases the sourcecode will be 2-6 kB. For a real big code maybe 20 to 50kB. No problem for even the smallest possible FS-partition-scheme. 

This would mean the sourcecode running on the ESP is always "at hand" if you ave the device.

I know there is the standard **data**-uploading tool and it can be done with it but it mixes up the real data and the sourcecode.

best regards Stefan

**Comment by earlephilhower** [comment]
That's an interesting idea, but there is unfortunately not a portable/supported way to get the source code that the Arduino toolchain compiles.  It's not sufficient to upload just a .ino file, as there are things like the core code and any included libraries as well.
