### ISSUE TITLE
Can it support the littlefs v2.9.3?

### ISSUE THREAD

**Issue by Linjieqiang** [earlephilhower/mklittlefs#42]
> D:\>mklittlefs --version
mklittlefs ver. 0.2.3-62-g975bd0f
Build configuration name: arduino-esp8266
LittleFS ver. v2.5.1
Extra build flags: -DSPIFFS_USE_MAGIC_LENGTH=0 -DSPIFFS_ALIGNED_OBJECT_INDEX_TABLES=1
LittleFS configuration:
  LFS_NAME_MAX: 32
  LFS_FILE_MAX: 2147483647
  LFS_ATTR_MAX: 1022

[v2.9.3](https://github.com/littlefs-project/littlefs/releases/tag/v2.9.3)

I'm new here. Does this project currently support the latest littlefs v2.9.3? I see that the version information can only be v2.5.1.

**Comment by earlephilhower** [comment]
Why would it need to?  If the on-flash format is the same then this should work fine.  If it's changed, then it would not be compatible with existing filesystems and would be a bad idea to migrate to, no?

**Comment by earlephilhower** [comment]
Unless the on flash format was changed without a change to the major revision number (seems very unlikely to me but I have not been following the project), then it should be readable just fine with a later version of the filesystem.  If you are concerned, simply clone the repo and update the littlefs submodule and build your own version.
