### ISSUE TITLE
mklittlefs-wasm 

### ISSUE THREAD

**Issue by rjjrbatarao** [earlephilhower/mklittlefs#56]
I have a requirement of serving littlefs config generation on a static website so I tried and started working from the wokwi sample. It works but still its limited may someone could port the full mkspiffs using my repo. `https://github.com/rjjrbatarao/littlefs-wasm/tree/master`, thank you for this awesome library. Im not that good in programming it took me days to make i work.

**Comment by earlephilhower** [comment]
Err, I think you need to talk to the project you forked your WASM app from.  We don't do any WASM or non-CLI binaries here.  Good luck!
