### ISSUE TITLE
mklittlefs x86_64-linux-gnu's version doesnt work on esp8266 After 3.2.0.

### ISSUE THREAD

**Issue by zerofo** [earlephilhower/mklittlefs#57]
mklittlefs x86_64-linux-gnu doesnt work on esp8266 after 3.2.0
4.0.0 & 4.0.1 (x86_64-linux-gnu) work well for esp32

**Comment by earlephilhower** [comment]
It says that in the release notes, so this is as expected.  The 8266 is practically (if not officially) EOL and nobody's bothered to update that Arduino core to the later LittleFS library or settings.  Earlier releases are still up for those stuck with the chip, which is the best we can do.
