### ISSUE TITLE
How can I burn image in uboot on spi-nand board if bad blocks is in the partition.

### ISSUE THREAD

**Issue by BRYCEPENG** [earlephilhower/mklittlefs#6]
My device is arm embedded linux system with spinand flash, I use mklittlefs tool to make image and burn image in uboot, whitch is working fine now.
According to my test, the designated size via using option '-s' is equal to the image size and also equal to the partition size.
Uboot burn code will skip a block when it detect bad block, so my question is that how can mklittlefs fix bad block when its image is equal to partition size, obviously uboot has no extra block in the parttition to burn code.
BTW: Compare to UBI file system, volume image size is less than partition size, and uboot burn code support bad block check.

**Comment by earlephilhower** [comment]
Sorry, I don't use ARM or UBI images.  The ARM forums may be your best bet for support.  Good luck!  -EFP3
